/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalcTabs: typeof import('./src/components/CalcTabs.vue')['default']
    ConcreteGradeCard: typeof import('./src/components/ConcreteGradeCard.vue')['default']
    CTAComponent: typeof import('./src/components/CTAComponent.vue')['default']
    FAQComponent: typeof import('./src/components/FAQComponent.vue')['default']
    Feetback: typeof import('./src/components/Feetback.vue')['default']
    Floor: typeof import('./src/components/TabsVariants/Floor.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    KeramzitCalc: typeof import('./src/components/TabsVariants/KeramzitCalc.vue')['default']
    KeramzitCard: typeof import('./src/components/KeramzitCard.vue')['default']
    NavigationComponent: typeof import('./src/components/NavigationComponent.vue')['default']
    PhoneComponent: typeof import('./src/components/PhoneComponent.vue')['default']
    PhoneInput: typeof import('./src/components/Inputs/PhoneInput.vue')['default']
    RequestModal: typeof import('./src/components/Requests/RequestModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UsernameInput: typeof import('./src/components/Inputs/UsernameInput.vue')['default']
    Variant1: typeof import('./src/components/TabsVariants/Variant1.vue')['default']
    Variant2: typeof import('./src/components/TabsVariants/Variant2.vue')['default']
    Variant3: typeof import('./src/components/TabsVariants/Variant3.vue')['default']
    Variant4: typeof import('./src/components/TabsVariants/Variant4.vue')['default']
    WhatsAppComponent: typeof import('./src/components/WhatsAppComponent.vue')['default']
  }
}
